
DATASET_DIR: "YOUR_PATH_TO_DATASET"
VAL_SPLIT: 0.1
BATCH_SIZE: 8 
DATA_WORKER_NUM: 4  
TRAIN_EPOCHS: 70 
OPT_CHANNELS: 4
SAR_CHANNELS: 2
PATCH_SIZE: 256
LORA_RANK: 32
TRAIN_SEQ_LEN: 6
MAX_VAL_SEQ_LEN: 20
SEED: 43
BASE_LR: 0.0002
